/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.12
 * Generated at: 2016-11-23 10:41:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import metier.JeuPileOuFace;

public final class PileFace_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<title> PileOuFace </title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<center>\n");
      out.write("\n");
      out.write("<h1> Pile ou Face </h1>\n");
      out.write("\n");

   JeuPileOuFace jeu = (JeuPileOuFace) session.getAttribute("jeu");
   if(jeu==null){
   jeu = new JeuPileOuFace();
   jeu.init();
   session.setAttribute("jeu",jeu);
   }else{
   String temp = request.getParameter("coup");
   
   if(temp != null  && (temp.equals("P") || temp.equals("F"))){
   jeu.play(temp.charAt(0));
   }
   }
   
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<p>Le premier arriv&eacute; &agrave; 10 a gagn&eacute;!<br>\n");
      out.write("Deux faces identiques je gagne, deux faces diff&eacute;rentes vous gagnez!</p>\n");
      out.write("\n");
      out.write("<p>\n");
      out.write("  ");
 if(jeu.getPointsHumain() == 0 && jeu.getPointsOrdi() == 0 ){ 
      out.write("\n");
      out.write("  Nous allons d&eacute;buter une nouvelle partie.\n");
      out.write("  ");
 }else{ 
      out.write("\n");
      out.write("  Vous venez de jouer\n");
      out.write("  ");
      out.print(jeu.getLastHumain());
      out.write("\n");
      out.write("  et l'ordi\n");
      out.write("  ");
      out.print(jeu.getLastOrdi());
      out.write('\n');
      out.write(' ');
      out.write(' ');
 } 
      out.write("\n");
      out.write("</p>\n");
      out.write("\n");
      out.write("<p> Scores ");
      out.print(jeu.getPointsHumain());
      out.write(" &agrave; ");
      out.print(jeu.getPointsOrdi());
      out.write("</p>\n");
      out.write("\n");
      out.write("<p> ");
 if(!jeu.termine()){ 
      out.write("\n");
      out.write("  Vous jouez\n");
      out.write("  <a href=\"PileFace.jsp?coup=P\">Pile</a>\n");
      out.write("  ou\n");
      out.write("  <a href=\"PileFace.jsp?coup=F\">Face</a>\n");
      out.write("  ?\n");
      out.write("  ");
 }else{ 
      out.write("\n");
      out.write("  <h1>\n");
      out.write("    Vous avez\n");
      out.write("    ");
 if(jeu.getPointsHumain()==10){ 
      out.write("\n");
      out.write("    gagn&eacute; !\n");
      out.write("    ");
 } else { 
      out.write("\n");
      out.write("    perdu !\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("    <a href=\"PileFace.jsp\">Rejouer?</a>\n");
      out.write("  </h1>\n");
      out.write("  ");
 session.setAttribute("jeu",null);
     } 
      out.write("\n");
      out.write("</p>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</center>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
